# Generated by Django 4.0 on 2021-12-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(default='Project 1', max_length=200),
            preserve_default=False,
        ),
    ]
